services:
  postgres:
    restart: unless-stopped
    image: postgis/postgis:18-3.6
    container_name: iot4ag-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-iot4ag-db}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-iot4ag-db} -h localhost -p 5432",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  rust-server:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-iot4ag-db}?sslmode=prefer
      SERVER_HOST: ${SERVER_HOST:-0.0.0.0}
      SERVER_PORT: ${SERVER_PORT:-80}
      STATIC_FILES_DIR: ${STATIC_FILES_DIR:-/frontend}
    ports:
      - "80:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge
